//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace codingfreaks.DatabaseUnitTests.Data.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerCustomerGroup
    {
        public long Id { get; set; }
        public long CustomerId { get; set; }
        public long CustomerGroupId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerGroup CustomerGroup { get; set; }
    }
}
